### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [RainixSTR/JAVA-grep#1]
1. `-r` - это флаг, а не опция с аргументом (у Вас вроде сначала так и было). То есть она должна быть `boolean`.
1. Сделайте нормальные аргументы `word` и `file`, а не массив.
1. `Grep` тоже должен принимать `-r` как флаг, а не как строку с регулярным выражением.
1. С файлом лучше работать через try-with-resources.
1. Собственно, регулярные выражения Вы никак сейчас не ищете, только простой текст.

**Comment by maximpetrov** [comment]
1. Зачем Вы сделали `found` полем, ещё и `static`?
1. https://github.com/RainixSTR/JAVA-grep/blob/4a7bf8f8f925225c7c78edc90441ec725e4818dd/src/Grep/Grep.java#L40-L42 Это не будет работать для поиска по регулярному выражению. Стоит использовать флаги `Pattern.compile`.
1. https://github.com/RainixSTR/JAVA-grep/blob/4a7bf8f8f925225c7c78edc90441ec725e4818dd/src/Grep/Grep.java#L46 Эта строка вообще ничего не делает.
1. Вообще, менять `pattern` для каждой строки - плохая идея. Флаги известны заранее, от строки ничего не зависит, так что внутри цикла `pattern` не должен меняться.
1. Вы зачем-то удалили тесты.

**Comment by RainixSTR** [comment]
1. Переменную found использую в тестах для сравнения с ожидаемым в качестве переменной Actual, поэтом модификаторы public static, иначе ее просто не видно в GrepTests
5. Переписал тесты. Видимо, не выгрузились

**Comment by maximpetrov** [comment]
1. Во-первых, тесты пишутся для программы, а не программа для тестов, так что делать что-то в программе исключительно ради тестов не самая хорошая практика, а тем более грубо нарушать инкапсуляцию. В крайнем случае его можно сделать package-private и не static. Во-вторых, мне всё ещё не совсем понятно, зачем делать его полем, если его возвращает `grep()`. Подозреваю, что Вы пытаетесь `main` целиком протестировать, но тогда и проверять нужно вывод в консоль.
1. Сделайте так, чтобы они всё-таки выгрузились

**Comment by RainixSTR** [comment]
1. Исправил
2. 2, 3 и 4 - Переделал создание переменной для фильтрации как для случая с флагом -r, так и с его отсутствием
3. Загрузил тесты :)

**Comment by maximpetrov** [comment]
1. `found` у Вас уже не `static`, но всё равно поле. Сделайте его локальной переменной.
1. `Pattern.CASE_INSENSITIVE` - этот флаг работает только для латиницы, добавьте `Pattern.UNICODE_CASE`, чтобы работало для всех языков.
1. Было бы лучше, если бы Вы всё-таки сделали `Pattern` в любом случае, как в прошлый раз и пытались. Нужно только правильно воспользоваться `Pattern.quote`. Тогда в цикле проверки Вам не придётся анализировать `-r` и `-i`.

**Comment by RainixSTR** [comment]
1. Сделал `found` локальной переменной
2. Добавил флаг `UNICODE_CASE`
3. Переписал код и сделал случаи для поиска с `-r` и без него через переменную типа `Pattern`

**Comment by maximpetrov** [comment]
1. Вы не сделали `found` локальной переменной, Вы просто сделали его package-private.
1. Флаги нужно объединять через `|`, сейчас у Вас как будто нет обоих флагов. Сейчас тест работает потому, что в регулярных выражениях Вы не используете больших букв, а строку Вы дополнительно переводите в нижний регистр. Кстати, это недостаток Ваших тестов.
1. Если Вы сначала проверите флаг `-r`, не создавая `Pattern`, а просто экранировав строку, а потом уже проверите `-i` и создадите `Pattern`, то не нужно будет проверять `-i` в цикле.

**Comment by RainixSTR** [comment]
1. Переместил `found` в `grep()`
2. Исправил `&` на `|`. Добавил тест для проверки флагов `-i` и `-r`
3. Исправил
